name: Deploy to Streamlit

on:
    push:
        branches:
            - main # Esse workflow será disparado sempre que houver um push para o branch 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest # Usar uma máquina virtual Ubuntu mais recente para rodar o processo

        steps:
            # Etapa 1: Realiza o checkout do código do repositório
            - name: Checkout repository
              uses: actions/checkout@v2

            # Etapa 2: Configura o Python no ambiente de execução
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8" # Você pode escolher outra versão do Python, se necessário

            # Etapa 3: Instala as dependências do projeto
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt  # Instalar as dependências do projeto listadas no 'requirements.txt'

            # Etapa 4: Configura a variável de ambiente GOOGLE_CREDENTIALS com o segredo do GitHub
            - name: Set up GOOGLE_CREDENTIALS environment variable
              run: echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}" >> $GITHUB_ENV

            # Etapa 5: Executa o Streamlit App
            - name: Run Streamlit app
              run: |
                  streamlit run app.py  # Roda o aplicativo Streamlit com o comando adequado
